# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "PrestaShop Docs theme"
license = "MIT"
licenselink = "https://github.com/PrestaShop/ps-docs-theme/blob/main/LICENSE.md"
description = "PrestaShop Documentation theme"
homepage = "https://github.com/PrestaShop/ps-docs-theme"
repo = "https://github.com/PrestaShop/ps-docs-theme"
tags = ["documentation", "prestashop"]
features = []
min_version = 0.25

[author]
  name = "PrestaShop SA and Contributors"
  homepage = "http://www.prestashop-project.org/"

[original]
  name = "Mathieu Cornic"
  homepage = "http://matcornic.github.io/"
  repo = "https://github.com/matcornic/hugo-theme-learn/"
